# step20_ingress_metallb/05-ingress-rule.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rule
spec:
  # 배포한 ingress-controller 와 연결고리가 되는 IngressClassName: nginx
  ingressClassName: nginx
  rules:
  - host: example.com
    http:
      # nginx 는 L7 장비이기 때문에 요청경로, 요청 url 등의 정보를 모두 인식할 수 있다
      paths:
      - path: /market     # /market 이라는 접두어로 인식, 뒤에 다른 경로가 추가 되어도 된다
        pathType: Prefix
        backend:
          service: 
            name: svc-market-app  # market pod 로 갈 수 있는 서비스 이름을 명시
            port:
              number: 8000
      - path: /posts       # /posts 이라는 접두어로 인식, 뒤에 다른 경로가 추가 되어도 된다
        pathType: Prefix
        backend:
          service: 
            name: svc-post-app  # post pod 로 갈 수 있는 서비스 이름을 명시
            port:
              number: 8000
      - path: /           # / 이라는 접두어로 인식, 뒤에 다른 경로가 추가 되어도 된다
        pathType: Prefix
        backend:
          service: 
            name: svc-index-app  # index pod 로 갈 수 있는 서비스 이름을 명시
            port:
              number: 80
      